### ISSUE TITLE
Could you Docker-ize ?

### ISSUE THREAD

**Issue by Glavic** [vascowhite/routemap#7]
Create Docker image for this project?

**Comment by vascowhite** [comment]
Probably, when it is ready. It is early days and I still have a number of issues with it. It would definately ease installation as getting Basemap is a bit of a palaver. I'm looking at Cartopy at the moment, to see if that makes things easier.

Thanks for the interest, I know the code isn't great, but it is the first real thing I've written in python and it is getting better.
